### ISSUE TITLE
Does Not Work On MacOS

### ISSUE THREAD

**Issue by sylv256** [mineLdiver/smoothbeta#2]
L "performance" mod
```
[23:29:54] [Minecraft main thread/ERROR] (FabricLoader) Uncaught exception in thread "Minecraft main thread"
java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path: /Users/sylv/Library/Application Support/PrismLauncher/instances/babric-b1.7.3/natives
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?]
	at java.lang.System.loadLibrary(System.java:1989) ~[?:?]
	at org.lwjgl.Sys$1.run(Sys.java:72) ~[lwjgl-2.9.4-babric.1.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.4-babric.1.jar:?]
	at org.lwjgl.Sys.loadLibrary(Sys.java:96) ~[lwjgl-2.9.4-babric.1.jar:?]
	at org.lwjgl.Sys.<clinit>(Sys.java:117) ~[lwjgl-2.9.4-babric.1.jar:?]
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135) ~[lwjgl-2.9.4-babric.1.jar:?]
	at net.minecraft.client.Minecraft.method_2106(Minecraft.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:716) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by sylv256** [comment]
user error
